server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: error
    org.springframework.boot: error
    com.weyong: debug
oneNetServer:
  name: firstServer
  oneNetPort: 9527
  contexts:
    -
      contextName: weyong
      internetPort: 83
      zip: true
      aes: false
    -
      contextName: mstsc
      internetPort: 56789
      zip: true
      aes: false
