server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: error
    org.springframework.boot: error
    com.weyong: debug
    io.netty.handler.logging: debug
oneNetClient:
  serverName: localhost
  reconnectAfterNSeconds: 7
  serverConfigs:
    -
      hostName: localhost
      oneNetPort: 9527
      contexts:
        -
          contextName: weyong
          localhost: localhost
          port: 88
          localPool: true
          poolConfig:
            maxIdle: 50
            minIdle: 30
            maxTotal: 1024
            blockWhenExhausted: true
            fireness: true
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: false
            maxWaitMillis: 100
            timeBetweenEvictionRunsMillis: 1000
        -
          contextName: mstsc
          localhost: localhost
          port: 3389
          localPool: false
        -
          contextName: test1
          localhost: localhost
          port: 88
          localPool: true
          poolConfig:
            maxIdle: 50
            minIdle: 30
            maxTotal: 1024
            blockWhenExhausted: true
            fireness: true
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: false
            maxWaitMillis: 100
            timeBetweenEvictionRunsMillis: 1000
        -
          contextName: test2
          localhost: localhost
          port: 82
          localPool: true
          poolConfig:
            maxIdle: 50
            minIdle: 30
            maxTotal: 1024
            blockWhenExhausted: true
            fireness: true
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: false
            maxWaitMillis: 100
            timeBetweenEvictionRunsMillis: 1000