server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: error
    org.springframework.boot: error
    com.weyong: debug
    io.netty.handler.logging: debug
oneNetClient:
  serverName: localhost
  reconnectAfterNSeconds: 7
  serverConfigs:
    -
      hostName: localhost
      oneNetPort: 9527
      contexts:
        -
          contextName: weyong
          localhost: localhost
          port: 88
          localPool: true
        -
          contextName: mstsc
          localhost: localhost
          port: 3389
          localPool: false
        -
          contextName: test1
          localhost: localhost
          port: 88
          localPool: false
        -
          contextName: test2
          localhost: localhost
          port: 82
          localPool: false